version: '3'

services:
  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    expose:
      - 3306
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - nodenet
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=docker
      - MYSQL_ROOT_PASSWORD=docker
    
  api:
    container_name: api
    build:
      context: ./src
    depends_on:
      - database
    tty: true
    volumes:
      - ./src:/usr/src/app
    entrypoint: dockerize -wait tcp://database:3306 -timeout 30s sh -c "npm install && node index.js"
    networks:
      - nodenet

  nginx:
    container_name: nginx
    build: 
      context: nginx/.
    depends_on:
      - api
    networks:
      - nodenet
    ports:
      - "8080:80"

networks:
  nodenet:
    driver: bridge